version: '2.0'
services: 
    web:
        image: nginx:1.13.0-alpine
        container_name: wrk-nginx
        restart: always
        ports: 
        - "80:80"
        - "443:443"
        volumes: 
        - ./html/:/usr/share/nginx/html
        - ./conf:/etc/nginx/conf.d
